#!/bin/bash
set -e

echo "<<<<< Install pip package spidev for root user"
/usr/bin/python3 -m pip install spidev==3.6

# We need to change to the directory where requirements.txt resides, so the
#   pyjaia path works
pushd /usr/share/jaiabot/python
    /usr/bin/python3 -m venv venv

    source venv/bin/activate
    pip3 install wheel
    pip3 install -r requirements.txt

    deactivate
popd

#DEBHELPER#

exit 0
